language: c++

matrix:
  include:
    - os: linux
      compiler: gcc # default version
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-4.9
      env: MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-5
      env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-6
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-7
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-7
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

env:
  global:
    - MAKEFLAGS="-j2"
    - CATCH_DIR="~/catch"
    - CATCH_REMOTE="https://github.com/catchorg/Catch2.git"

git:
  depth: 1

before_install:
  - eval "${MATRIX_EVAL}" # determine the compiler, overriding defaults

install:
  - git clone ${CATCH_REMOTE} ${CATCH_DIR}
  - pushd ${CATCH_DIR}
  - git checkout $(git describe --tags --abbrev=0)
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING:BOOL=FALSE ..
  - make
  - sudo make install
  - popd # reset current directory

script:
  - export VERBOSE=1
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test

after_failure: cat ./Testing/Temporary/LastTest.log
