language: c++

#os:
#  - linux
#  - osx
#

matrix:
  include:
    - os: linux
      compiler: gcc # default version
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-4.9
      env: MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-5
      env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-6
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-7
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-7
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}" # determine the compiler
  - BUILD_THREADS=`lscpu -p | grep -c '^[0-9]'` # get number of hw threads
  - echo ${BUILD_THREADS}

install:
  - CATCH_DIR=/tmp/catch CATCH_REMOTE=https://github.com/catchorg/Catch2.git
  - git clone ${CATCH_REMOTE} ${CATCH_DIR}
  - cd ${CATCH_DIR}
  - git checkout $(git describe --tags --abbrev=0)
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING:BOOL=FALSE ..
  - make
  - sudo make install
  - cd ${TRAVIS_BUILD_DIR} # reset current directory

script:
  - export VERBOSE=1
  - mkdir build
  - cd build
  - cmake ..
  - make -j${BUILD_THREADS}
  - make test -j${BUILD_THREADS}

after_failure: cat ./Testing/Temporary/LastTest.log

git:
  depth: 1
